name: SmuView MXE Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/knarfs/sigrok-mxe:latest

    strategy:
      matrix:
        target: ["i686", "x86_64"]

    env:
      TARGET: ${{ matrix.target }}
      DEBUG: 0

    steps:
      - name: Checkout sigrok-utils
        uses: actions/checkout@v2
        with:
          repository: knarfS/sigrok-util
          path: sigrok-util
          ref: github

      # Workaround
      - name: Install sudo package
        run: apt update && apt install sudo

      - name: Build dependencies
        shell: bash
        run: |
          sudo apt-get install -y doxygen
          cd sigrok-util/cross-compile/github-actions
          source sigrok-mxe-init-toolchain.sh
          ./sigrok-mxe-build-dependencies.sh

      - name: Checkout smuview
        uses: actions/checkout@v2
        with:
          path: smuview

      - name: Build smuview
        shell: bash
        run: |
          source sigrok-util/cross-compile/github-actions/sigrok-mxe-init-toolchain.sh
          cd smuview
          mkdir build
          cd build
          $CMAKE \
            -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DDISABLE_WERROR=y \
            -DENABLE_TESTS=y \
            ..
          make $PARALLEL $V
