name: SmuView MacOS Build

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  # The path where the compiled packages will be installed.
  INSTALL_DIR: "${{ github.workspace }}/sr"
  # Git URL for the sigrok dependencies
  SIGROK_REPO_BASE: "https://github.com/knarfS"
  # Build type for SmuView (Debug, Release, RelWithDebInfo, MinSizeRel)
  BUILD_TYPE: "Release"
  # Misc commands
  WGET: "wget -c --quiet"
  GIT_CLONE: "git clone --depth=1"

jobs:
  build:
    name: MacOS build (${{ matrix.compiler.compiler }})

    runs-on: macos-latest # macos-10.15

    strategy:
      matrix:
        compiler:
          - { compiler: GCC, cc: "gcc", cxx: "g++" }
          - { compiler: LLVM, cc: "llvm-gcc", cxx: "llvm-g++" }

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - name: Install dependencies
        run: |
          brew install autoconf automake autoconf-archive pkg-config \
            libtool libzip libusb libftdi hidapi nettle check doxygen swig \
            glib glibmm@2.66 cmake python3 boost qt@5 qwt

      - name: Checkout sigrok-utils
        uses: actions/checkout@v2
        with:
          repository: knarfS/sigrok-util
          path: sigrok-util
          ref: github

      - name: Build dependencies
        run: |
          cd sigrok-util/cross-compile/github-actions
          source sigrok-macos-init-toolchain.sh
          ./sigrok-macos-build-dependencies.sh

      - name: Checkout smuview
        uses: actions/checkout@v2
        with:
          path: smuview

      - name: Build smuview
        run: |
          source sigrok-util/cross-compile/github-actions/sigrok-macos-init-toolchain.sh
          mkdir -p smuview/build
          cd smuview/build
          PKG_CONFIG_PATH=$P cmake \
            -DCMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DDISABLE_WERROR=y \
            -DENABLE_TESTS=y \
            ..
          make $PARALLEL $V
          make install $V

      - name: Build DMG
        run: |
          # Source SmuView versions and names
          source smuview/build/contrib/config_version.sh
          cd sigrok-util/cross-compile/github-actions
          source sigrok-macos-init-toolchain.sh
          ./sigrok-macos-create-dmg.sh

      - name: Upload artifact
        # Only upload artifact for the LLVM build!
        if: startsWith(matrix.compiler.compiler, 'LLVM')
        uses: actions/upload-artifact@v2
        with:
          name: SmuView DMG
          path: sigrok-util/cross-compile/github-actions/SmuView*.dmg
