name: SmuView Build

on:
  push:
    paths-ignore:
      - "doxy/**"
      - "manual/**"
      - "stuff/**"
  pull_request:
    paths-ignore:
      - "doxy/**"
      - "manual/**"
      - "stuff/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  # The path where the compiled packages will be installed.
  INSTALL_DIR: "${{ github.workspace }}/sr"
  # Git URL for the sigrok dependencies
  SIGROK_REPO_BASE: "https://github.com/sigrokproject"
  # Build type for SmuView (Debug, Release, RelWithDebInfo, MinSizeRel)
  BUILD_TYPE: "Release"
  # Misc commands
  WGET: "wget -c --quiet"
  GIT_CLONE: "git clone --depth=1"
  # AppImage related properties are set as container ENVs if needed.

jobs:

  build_mxe:
    name: SmuView MXE build (${{ matrix.target.target }})

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/knarfs/sigrok-mxe:latest

    strategy:
      matrix:
        target:
          - { target: "i686", nsis_param: "" }
          - { target: "x86_64", nsis_param: "-DPE64=1" }

    env:
      TARGET: ${{ matrix.target.target }}
      DEBUG: 0
      # Download python from sigrok.org and smth is wrong with the cert
      WGET: "wget -c --quiet --no-check-certificate"

    steps:
      - name: Checkout sigrok-utils
        uses: actions/checkout@v2
        with:
          repository: Lightwars/sigrok-util
          path: sigrok-util
          ref: github

      - name: Build dependencies
        run: |
          # Zadig (we ship this with frontends for easy driver switching).
          $WGET https://github.com/pbatard/libwdi/releases/download/b721/zadig-2.4.exe -O $INSTALL_DIR/zadig.exe
          $WGET https://github.com/pbatard/libwdi/releases/download/v1.2.5/zadig_xp-2.2.exe -O $INSTALL_DIR/zadig_xp.exe
          
          cd sigrok-util/cross-compile/github-actions
          source sigrok-mxe-init-toolchain.sh
          ./sigrok-mxe-build-dependencies.sh

      - name: Checkout smuview
        uses: actions/checkout@v2
        with:
          path: smuview

      - name: Build smuview
        run: |
          source sigrok-util/cross-compile/github-actions/sigrok-mxe-init-toolchain.sh
          mkdir -p smuview/build
          cd smuview/build
          $CMAKE \
            -DCMAKE_INSTALL_PREFIX:PATH=$INSTALL_DIR \
            -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
            -DDISABLE_WERROR=FALSE \
            -DENABLE_TESTS=TRUE \
            ..
          make $PARALLEL $V
          make install/strip $V

      - name: Build NSIS installer
        run: |
          source sigrok-util/cross-compile/github-actions/sigrok-mxe-init-toolchain.sh

          cp sigrok-util/cross-compile/github-actions/contrib-mxe/FileAssociation.nsh smuview/build/contrib
          makensis ${{ matrix.target.nsis_param }} smuview/build/contrib/smuview_cross.nsi

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SmuView NSIS ${{ matrix.target.target }} installer
          path: smuview/build/contrib/SmuView*installer.exe
          
      - name: Upload artifact2
        uses: actions/upload-artifact@v2
        with:
          name: sigrok-cli NSIS ${{ matrix.target.target }} installer
          path: ${{ env.INSTALL_DIR }}/sigrok-cli*installer.exe


  publish:
    name: SmuView publish

    runs-on: ubuntu-latest

    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
    needs:
      - build_mxe

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Upload artifacts and create (continuous) release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/SmuView-*.*
